[package]
name="taybenlor/runno-clang"
version="0.1.2"
description="Clang is a compiler front end for the C, C++, Objective-C and Objective-C++ programming languages"
readme = "README.md"
repository = "https://github.com/taybenlor/clang"

[[module]]
name="clang"
source="clang.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[module]]
name="wasm-ld"
source="wasm-ld.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
name="runno-clang"
module="clang"

[[command]]
name="runno-wasm-ld"
module="wasm-ld"

[fs]
"/sys"="sysroot"
